// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful';
import { Document } from '@contentful/rich-text-types';

export interface IContentBlockFields {
  /** Title */
  title: string;

  /** Text */
  text: string;

  /** Link */
  link?: ILink | undefined;

  /** Align left */
  alignLeft?: boolean | undefined;

  /** Image */
  image?: IImage | undefined;
}

export interface IContentBlock extends Entry<IContentBlockFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'contentBlock';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IHomePageFields {
  /** Title */
  title: string;

  /** metaDescription */
  metaDescription?: string | undefined;

  /** Description */
  description: string;

  /** Header image */
  headerImage?: IImage | undefined;

  /** Content blocks */
  contentBlocks: IContentBlock[];
}

export interface IHomePage extends Entry<IHomePageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'homePage';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IImageFields {
  /** Title */
  title: string;

  /** Image */
  image: Asset;

  /** Focal point */
  focalPoint: Record<string, any>;
}

export interface IImage extends Entry<IImageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'image';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ILinkFields {
  /** Title */
  title?: string | undefined;

  /** page */
  page: IHomePage | IPage;
}

export interface ILink extends Entry<ILinkFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'link';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface INavigationFields {
  /** Title */
  title: string;

  /** Links */
  links: INavigationLink[];
}

export interface INavigation extends Entry<INavigationFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'navigation';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface INavigationLinkFields {
  /** Title */
  title: string;

  /** Page */
  page: IHomePage | IPage;
}

export interface INavigationLink extends Entry<INavigationLinkFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'navigationLink';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IPageFields {
  /** Slug */
  slug: string;

  /** Title */
  title: string;

  /** metaDescription */
  metaDescription?: string | undefined;

  /** Description */
  description?: string | undefined;

  /** Content blocks */
  contentBlocks: IContentBlock[];
}

export interface IPage extends Entry<IPageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'page';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export type CONTENT_TYPE = 'contentBlock' | 'homePage' | 'image' | 'link' | 'navigation' | 'navigationLink' | 'page';

export type LOCALE_CODE = 'en-US' | 'nl-NL';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US';
