name: Lint

on:
  push:
    branches:
      - main
      - develop

jobs:
  run_linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm i && npm run lint
